### ISSUE TITLE
puppet manifest creation is confusing

### ISSUE THREAD

**Issue by ajoga** [aws-samples/aws-service-catalog-tools-workshop#46]
For this step : https://service-catalog-tools-workshop.com/30-how-tos/50-every-day-use/190-creating-a-manifest.html

It's not explicitly said that the created file should be empty. Furthermore, the [bottom screenshot](https://service-catalog-tools-workshop.com/how-tos/creating-and-provisioning-a-product/CommitChanges.png) contains what looks like to be the bottom of the file we'd be adding, and it has contents.

Proposed fix : either state that the file should be empty, or explicit a content to input.

**Comment by eamonnfaherty** [comment]
thanks for taking the time to report this. it has been fixed.
