### ISSUE TITLE
boostrap the spoke is missing

### ISSUE THREAD

**Issue by ajoga** [aws-samples/aws-service-catalog-tools-workshop#47]
https://service-catalog-tools-workshop.com/30-how-tos/50-every-day-use/192-adding-an-account.html 

https://github.com/aws-samples/aws-service-catalog-tools-workshop/blame/master/workshop/content/30-how-tos/50-every-day-use/192-adding-an-account/_index.md#L16

# Description

To add an account to share portfolio with the puppet project, one prerequisite is to "boostrap the spoke". It's something that has not be done if following the workshop in its logical order ; furthermore there is no page about that in the workshop. 

I found [this other documentation](https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/bootstrapping_spokes.html) to do it.

# Suggested fixes

- Link the above documentation as prerequisite
- Add an howto doc that paraphrases the above doc
- ... ?

**Comment by eamonnfaherty** [comment]
thanks for taking the time to report this. it has been fixed.

the fix is not amazing but it works for now.  we will be improving this soon.
