### ISSUE TITLE
Adding an account : confusing screenshot

### ISSUE THREAD

**Issue by ajoga** [aws-samples/aws-service-catalog-tools-workshop#48]
# Description

The [Howto](https://service-catalog-tools-workshop.com/30-how-tos/50-every-day-use/192-adding-an-account.html) to add an account to the manifest file of the puppet projects is illustrated by a screenshot of the Factory repository. 

# Suggested fix

Update the screenshot to show the Puppet account

**Comment by eamonnfaherty** [comment]
thanks for taking the time to report this. it has been fixed.
