### ISSUE TITLE
Deploy stage link does not work

### ISSUE THREAD

**Issue by ritesh** [aws-samples/aws-service-catalog-tools-workshop#57]
## Steps to reproduce

Follow the workshop to create your first product. When the aws-config-instance-types-v1-pipeline runs, the Deploy stage gives you a link to jump to service-catalog directly to see the product

### Expected results
When I click on the link in the deploy stage, it should take me to the product.

### Actual results
I get an "Error: Product details not found." 

This is the link that it produces: https://eu-west-1.console.aws.amazon.com/servicecatalog/home?#/admin-products/details?productId=prod-gahetlx7tdnza.

I think that the region param is missing but not sure if that's a red herring: 

https://eu-west-1.console.aws.amazon.com/servicecatalog/home?region=eu-west-1&isSceuc=false#admin-products/prod-gahetlx7tdnza
 
If I want to list products via the SC UI, this is the link the console produces: https://eu-west-1.console.aws.amazon.com/servicecatalog/home?region=eu-west-1&isSceuc=false#admin-products

**Comment by mckayjuk** [comment]
Checking

**Comment by mckayjuk** [comment]
There is an error in the URL in the Deploy Stage.

**Failing URL**
https://eu-west-1.console.aws.amazon.com/servicecatalog/home?region=eu-west-1&isSceuc=false#admin-products/prod-id

**Working URL**
https://eu-west-1.console.aws.amazon.com/servicecatalog/home?region=eu-west-1&isSceuc=false#admin-products/**_details?productId=_**prod-Id

**Comment by ritesh** [comment]
Closing this out, as I think it was resolved. =)
