### ISSUE TITLE
Clarify that the hub and spoke are the same account

### ISSUE THREAD

**Issue by ritesh** [aws-samples/aws-service-catalog-tools-workshop#60]
For the workshop, we are using the same account as a hub and spoke. We need to call this out multiple times to avoid confusion, I think it may not be very obvious.

First place to call this out: 
`40-reinvent2019/100-task-1/100-create-the-control.html`

And then when we create the manifest: 
`40-reinvent2019/100-task-1/200-provision-the-control.html`

I can create  PR for it

**Comment by ritesh** [comment]
Clarify hub and spoke are same: 40-reinvent2019/150-task-2/200-provision-the-control.html

**Comment by ritesh** [comment]
Clarify hub and spoke are the same here: 40-reinvent2019/150-task-2/300-create-the-product.html

**Comment by eamonnfaherty** [comment]
please raise the PR
