### ISSUE TITLE
CFNNag test doesn't fail as expected

### ISSUE THREAD

**Issue by mattsnell** [aws-samples/aws-service-catalog-tools-workshop#81]
## Steps to reproduce
- Go to the 2019 workshop:  https://service-catalog-tools-workshop.com/reinvent2019/
- Follow the workshop through the Create the Product section under Data Governance https://service-catalog-tools-workshop.com/40-reinvent2019/150-task-2/300-create-the-product.html

### Expected results
I expected the CFNNag test to fail

### Actual results
I observed that the CFNNag test succeeded

See https://113dd118-e3fb-11eb-8877-acde48001122.s3.amazonaws.com/tmp/build-output-cfn-nag.txt for the build log results

**Comment by eamonnfaherty** [comment]
This was fixed in a factory release.
