### ISSUE TITLE
UPLOAD_ARTIFACTS	 Failed CLIENT_ERROR: no matching artifact paths found

### ISSUE THREAD

**Issue by SergiyShevchenk** [aws-samples/aws-service-catalog-tools-workshop#83]
## Steps to reproduce
create a VPC pipeline fails

### Expected results
I observed 

### Actual results

Attempting uninstall: colorama
--
197 | Found existing installation: colorama 0.4.3
198 | Uninstalling colorama-0.4.3:
199 | Successfully uninstalled colorama-0.4.3
200 | ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
201 | cookiecutter 1.7.3 requires requests>=2.23.0, but you have requests 2.22.0 which is incompatible.
202 | awscli 1.20.6 requires botocore==1.21.6, but you have botocore 1.17.33 which is incompatible.
203 | awscli 1.20.6 requires colorama<0.4.4,>=0.2.5, but you have colorama 0.4.4 which is incompatible.
204 | awscli 1.20.6 requires s3transfer<0.6.0,>=0.5.0, but you have s3transfer 0.3.3 which is incompatible.
205 | aws-sam-cli 1.27.2 requires click~=7.1, but you have click 7.0 which is incompatible.
206 | aws-sam-cli 1.27.2 requires requests==2.25.1, but you have requests 2.22.0 which is incompatible.
207 | Successfully installed MarkupSafe-1.1.1 PyYAML-5.4 astroid-2.4.2 aws-service-catalog-factory-0.64.0 better-boto-0.36.0 boto3-1.14.33 botocore-1.17.33 certifi-2020.6.20 cfn-flip-1.2.1 chardet-3.0.4 click-7.0 colorama-0.4.4 colorclass-2.2.0 deepmerge-0.3.0 docopt-0.6.2 docutils-0.14 enum34-1.1.10 idna-2.8 isort-4.3.21 lazy-object-proxy-1.4.3 lockfile-0.12.2 luigi-2.8.6 mccabe-0.6.1 pykwalify-1.7.0 pylint-2.5.0 python-daemon-2.1.2 python-dateutil-2.8.1 requests-2.22.0 s3transfer-0.3.3 six-1.15.0 terminaltables-3.1.0 toml-0.10.1 tornado-4.5.3 troposphere-2.6.4 typed-ast-1.4.1 urllib3-1.22 wrapt-1.12.1
208 | WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
209 | WARNING: You are using pip version 21.1.2; however, version 21.2.4 is available.
210 | You should consider upgrading via the '/root/.pyenv/versions/3.7.10/bin/python3.7 -m pip install --upgrade pip' command.
211 |  
212 | [Container] 2021/08/28 02:49:03 Phase complete: INSTALL State: SUCCEEDED
213 | [Container] 2021/08/28 02:49:03 Phase context status code:  Message:
214 | [Container] 2021/08/28 02:49:03 Entering phase PRE_BUILD
215 | [Container] 2021/08/28 02:49:03 Phase complete: PRE_BUILD State: SUCCEEDED
216 | [Container] 2021/08/28 02:49:03 Phase context status code:  Message:
217 | [Container] 2021/08/28 02:49:03 Entering phase BUILD
218 | [Container] 2021/08/28 02:49:03 Running command servicecatalog-factory --info generate .
219 | INFO MainThread Generating
220 | INFO MainThread logging configured by default settings
221 | INFO: Done scheduling tasks
222 | INFO MainThread Done scheduling tasks
223 | INFO: Running Worker with 10 processes
224 | INFO MainThread Running Worker with 10 processes
225 | INFO: Worker Worker(salt=794597043, workers=10, host=b4c11f922991, username=root, pid=288) was stopped. Shutting down Keep-Alive thread
226 | INFO Thread-1 Worker Worker(salt=794597043, workers=10, host=b4c11f922991, username=root, pid=288) was stopped. Shutting down Keep-Alive thread
227 | INFO:
228 | ===== Luigi Execution Summary =====
229 |  
230 | Did not schedule any tasks
231 |  
232 | ===== Luigi Execution Summary =====
233 |  
234 | INFO MainThread
235 | ===== Luigi Execution Summary =====
236 |  
237 | Did not schedule any tasks
238 |  
239 | ===== Luigi Execution Summary =====
240 |  
241 | +--------+------+------------------------+----------+
242 | \| Result \| Task \| Significant Parameters \| Duration \|
243 | +--------+------+------------------------+----------+
244 |  
245 | [Container] 2021/08/28 02:49:04 Phase complete: BUILD State: SUCCEEDED
246 | [Container] 2021/08/28 02:49:04 Phase context status code:  Message:
247 | [Container] 2021/08/28 02:49:04 Entering phase POST_BUILD
248 | [Container] 2021/08/28 02:49:04 Phase complete: POST_BUILD State: SUCCEEDED
249 | [Container] 2021/08/28 02:49:04 Phase context status code:  Message:
250 | [Container] 2021/08/28 02:49:04 Expanding base directory path: .
251 | [Container] 2021/08/28 02:49:04 Assembling file list
252 | [Container] 2021/08/28 02:49:04 Expanding .
253 | [Container] 2021/08/28 02:49:04 Expanding file paths for base directory .
254 | [Container] 2021/08/28 02:49:04 Assembling file list
255 | [Container] 2021/08/28 02:49:04 Expanding results/*/*
256 | [Container] 2021/08/28 02:49:04 Expanding output/*/*
257 | [Container] 2021/08/28 02:49:04 Expanding portfolios/*
258 | [Container] 2021/08/28 02:49:04 Phase complete: UPLOAD_ARTIFACTS State: FAILED
259 | [Container] 2021/08/28 02:49:04 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found

**Comment by eamonnfaherty** [comment]
Thanks for raising this. 

It looks like your workflow didn't execute any commands. 

I would guess it is because you do not have a file matching *.yaml in a portfolios directory. 

Could you please check this and let me know.

**Comment by SergiyShevchenk** [comment]
should it be stacks or portfolios?
i'm doing 2021 workshop

**Comment by SergiyShevchenk** [comment]
aha, i see now...
could you please update with the following:
1. Codecommit
1.1. Create ServiceCatalogFactory/portfolios
1.2. create yaml file with whatever name but yaml extension
1.3. create <product name> repo with the name stack.template.yaml which is must be that name

that will do the trick

**Comment by SergiyShevchenk** [comment]
the issue is fixed
